#!/usr/bin/env ruby
require_relative "../lib/ferret"


bash(name: :setup, stdin: <<'EOF')
  heroku create $SERVICE_APP_NAME
EOF

run_every_time do
  bash(name: :http_push, pattern: /Heroku receiving push/, stdin: <<'EOF')
    TARGET_APP= 
    rm -rf $SERVICE_APP_NAME
    mkdir $SERVICE_APP_NAME
    cd $SERVICE_APP_NAME
    git init
    date > now
    git add now
    git commit -m initial
    git push --force https://code.heroku.com/$SERVICE_APP_NAME.git master
EOF
end

run forever: true