#!/usr/bin/env ruby
require_relative "../lib/ferret"

bash(retry: 2, name: :setup, stdin: <<'EOF')
  heroku info || {
    heroku create --app $TARGET_APP
    heroku manager:transfer --to $ORG --app $TARGET_APP
  }
EOF

bash(retry: 2, name: :run, stdin: <<'EOSH')
  heroku run true --app $TARGET_APP
EOSH
