#!/usr/bin/env ruby

require_relative "../lib/ferret"

bash(retry: 2, name: "heroku-info-create", stdin: <<'EOF')
  heroku info --app $TARGET_APP || {
    heroku create $TARGET_APP  --stack bamboo                             \
      && heroku plugins:install https://github.com/heroku/manager-cli.git \
      && heroku manager:transfer --app $TARGET_APP --to ferret
  }
EOF

bash(retry: 2, name: "init-commit", stdin: <<'EOF')
  git init app
  cd app
  git commit --allow-empty -m "empty"
EOF

bash(retry: 2, name: "push", stdin: <<'EOF')
  cd app
  git push -f git@heroku.com:$TARGET_APP.git master:test
EOF
