#!/usr/bin/env ruby

require_relative "../lib/ferret"

bash(retry: 2, name: :heroku_info_create, stdin: <<'EOF')
  heroku info --app $TARGET_APP || {
    heroku create $TARGET_APP                                             \
      && heroku plugins:install https://github.com/heroku/manager-cli.git \
      && heroku manager:transfer --app $TARGET_APP --to $ORG
  }
EOF

bash(name: :clone, pattern: /cloned an empty repository/, stdin: <<'EOF')
  rm -rf ./app
  git clone git@heroku.com:$TARGET_APP.git ./app
EOF
