#!/usr/bin/env ruby
require_relative "../lib/ferret"


bash(name: :setup, stdin: <<'EOF')
  mkdir testapp
  cd testapp
  git init
  heroku create $APP-service
  cd ../
EOF

run_every_time do
  bash(name: :http_push, pattern: /Heroku receiving push/, stdin: <<'EOF')
    TARGET_APP=$APP-service
    rm -rf $TARGET_APP
    mkdir $TARGET_APP
    cd $TARGET_APP
    git init
    date > now
    git add now
    git commit -m initial
    git push --force https://code.heroku.com/$TARGET_APP.git master
EOF
end