#!/usr/bin/env ruby
require_relative "../lib/ferret"

bash(retry: 2, name: :setup, stdin: <<'EOSTDIN')
  heroku info --app $TARGET_APP || {
    heroku create $TARGET_APP                                             \
      && heroku plugins:install https://github.com/heroku/manager-cli.git \
      && heroku manager:transfer --app $TARGET_APP --to $ORG               \
      && cd $FERRET_DIR/app/basic_http                                     \
      && bundle install                                                   \
      && heroku build -r $TARGET_APP $FERRET_DIR/app/basic_http            \
      && heroku scale web=1 --app $TARGET_APP                              \
      && cd $FERRET_DIR
    }
EOSTDIN


bash(name: :consider_restart, timeout:50,stdin: <<'EESTD')
  #one in twenty times
  if [ $(($RANDOM % 20 )) -eq 1 ]; then
     heroku restart --app $TARGET_APP
  fi
  exit 0
EESTD


bash(name: :poll, timeout: 3900, stdin: <<'EOSH')
  set -x
  res=$( curl -w %{http_code} -s --output /dev/null http://${TARGET_APP}.herokuapp.com)
  [ $res == "200" ]
EOSH
