#!/usr/bin/env ruby

require_relative "../lib/ferret"

bash(retry: 1, name: :setup, stdin: <<'EOF')


run_every_time do
  bash(retry: 2, name: :clone, pattern: /cloned an empty repository/, stdin: <<'EOF')
    rm -rf ./tmp
    git clone https://code.heroku.com/$TARGET_APP.git ./tmp
EOF
end

run time: :forever