#!/usr/bin/env ruby

require_relative "../lib/ferret"

bash(name: "ssh-invalid-fingerprint", pattern: /fingerprint/, status: nil, stdin: <<'EOF')
  ssh git@heroku.com "git-receive-pack 'blog.git'"
EOF
