#!/usr/bin/env ruby
require_relative "../lib/ferret"

bash(retry: 2, name: :setup, stdin: <<'EOF')
  function heroku() { /usr/bin/heroku "$@" --app $TARGET_APP; }

  heroku info || {
    heroku plugins:install https://github.com/ddollar/heroku-anvil
    heroku plugins:install git://github.com/heroku/manager-cli.git # TODO: rename heroku-manager.git
    heroku plugins:install git@github.com:heroku/heroku-sudo.git
    heroku plugins:install git://github.com/JacobVorreuter/heroku-routing.git

    # create, configure, build, release and scale app
    heroku create

    heroku config:set HEROKU_API_KEY=$(TARGET_APP=$FERRET_APP heroku config:get HEROKU_API_KEY) TARGET_APP=$TARGET_APP
    heroku sudo flags:add   compile-cluster
    heroku sudo labs:enable dot-profile-d
    heroku manager:transfer --to ferret

    ROUTE=$(heroku routes:create | tail -1)
    heroku routes:attach $ROUTE receive

    heroku build -r $TARGET_APP $FERRET_DIR/app/ssh_tcp_receive

    heroku scale receive=1
  }
EOF

bash(retry: 2, name: :connect, stdin: <<'EOF')
  set -x
  function heroku() { /usr/bin/heroku "$@" --app $TARGET_APP; }

  PORT=$(heroku routes | grep receive | cut -d ":" -f3 | cut -d " " -f1)
  USER=$(curl https://ferretapp.s3.amazonaws.com/ssh_tcp_receive_user)
  ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $USER@route.heroku.com -p $PORT true
EOF
