#!/usr/bin/env ruby
ENV["SERVICE_APP_NAME"]="f-git-clone-bamboo"
require_relative "../../lib/ferret"
uses_app empty:true, stack:"bamboo"

run_every_time do
  bash(name: :clone, pattern: /cloned an empty repository/, stdin: <<'EOF')
  rm -rf ./app
  git clone git@heroku.com:$SERVICE_APP_NAME.git ./app
EOF
end

run forever: true
