#!/usr/bin/env ruby
require_relative "../../lib/ferret"

uses_app empty:true

run_every_time do
  bash(name: :clone, pattern: /cloned an empty repository/, stdin: <<-'EOF')
    rm -rf ./app
    git clone ssh://git@gitproxy-default.herokussl.com:2222/$SERVICE_APP_NAME.git ./app
  EOF
end

run forever: true