#!/usr/bin/env ruby
require_relative "../../lib/ferret"


uses_app path: "#{ENV["FERRET_DIR"]}/app/basic_http"

bash(name: :git_init, stdin: <<-'EOSTDIN')
  rm -rf ./app
  cp -r $FERRET_DIR/app/basic_http ./app
  cd ./app
  git init && git add . && git commit -m "init"
EOSTDIN

run_every_time do
  bash(name: :push, pattern: /Launching\.\.\. done/, stdin: <<-'EOSTDIN')
    cd ./app
    git commit --allow-empty -m "empty"
    git push -f git@heroku.com:$SERVICE_APP_NAME.git master
  EOSTDIN
end

run forever: true