exec_converge:    bin/loop test/exec_converge
exec_run:         bin/loop test/exec_run
git_clone:        bin/loop test/git_clone
git_clone_bamboo: bin/loop test/git_clone_bamboo
git_clone_elb:    bin/loop test/git_clone_elb
librato:          bin/loop test/librato
perf_cpu:         bin/loop test/perf_cpu
perf_disk:        bin/loop test/perf_disk
perf_network:     bin/loop test/perf_network
ssh_fingerprint:  bin/loop test/ssh_fingerprint
ssh_path:         bin/loop test/ssh_path
ssh_tcp_receive:  bin/loop test/ssh_tcp_receive
