tests-dns-resolve: tests/dns/resolve
tests-git-clone: tests/git/clone
tests-git-clone-bamboo: tests/git/clone_bamboo
tests-git-clone-elb: tests/git/clone_elb
tests-git-push-ruby: tests/git/push_ruby
tests-http-curl: tests/http/curl
tests-http-recurl: tests/http/recurl
tests-oauth-redirect: tests/oauth/redirect
tests-perf-cpu: tests/perf/cpu
tests-perf-disk: tests/perf/disk
tests-perf-network: tests/perf/network
tests-ssh-fingerprint: tests/ssh/fingerprint
tests-ssh-path: tests/ssh/path 
tests-ssh-tcp-receive: tests/ssh/tcp_receive
