tests_dns_resolve: ./tests/dns/resolve
tests_git_clone: ./tests/git/clone
tests_git_clone_bamboo: ./tests/git/clone_bamboo
tests_git_clone_elb: ./tests/git/clone_elb
tests_git_push_ruby: ./tests/git/push_ruby
tests_http_curl: ./tests/http/curl
tests_http_recurl: ./tests/http/recurl
tests_oauth_redirect: ./tests/oauth/redirect
tests_perf_cpu: ./tests/perf/cpu
tests_perf_disk: ./tests/perf/disk
tests_perf_network: ./tests/perf/network
tests_ssh_fingerprint: ./tests/ssh/fingerprint
tests_ssh_path: ./tests/ssh/path
tests_ssh_tcp_receive: ./tests/ssh/tcp_receive
