#!/usr/bin/env ruby
require_relative "../lib/ferret"

bash(retry: 2, name: :setup, stdin: <<'EOF')
  function heroku() { $(which heroku) "$@" --app $TARGET_APP; }

  heroku info || {
    heroku plugins:install git://github.com/heroku/manager-cli.git

    heroku create
    heroku manager:transfer --to $ORG
  }
EOF

bash(retry: 2, name: :run, stdin: <<'EOSH')
  heroku run true --app $TARGET_APP
EOSH
