#!/usr/bin/env ruby
require_relative "../lib/ferret"

uses_app "../app/basic_http"


#make these function calls with ruby blocks
run_every_time do
  bash(name: :poll, timeout: 3900, stdin: <<-'EOSH')
    set -x
    res=$( curl -w %{http_code} -s --output /dev/null http://${TARGET_APP}.herokuapp.com)
    [ $res == "200" ]
  EOSH
end


run time: :forever