#!/usr/bin/env ruby
require_relative "../../lib/ferret"

uses_app path: "#{ENV["FERRET_DIR"]}/app/basic_http"

run_every_time do
  bash(name: :poll, timeout: 3900, stdin: <<-'EOSH')
    curl --fail http://${SERVICE_APP_NAME}.herokuapp.com -v
  EOSH
end

run forever: true