#!/usr/bin/env ruby
require_relative "../../lib/ferret"


uses_app path: "#{ENV["FERRET_DIR"]}/app/basic_http"

run_interval 10 do 
  bash(name: :consider_restart, timeout: 50, stdin: <<-'EOSH')
    heroku restart --app $SERVICE_APP_NAME
  EOSH
end

run_every_time do
  bash(name: :poll, timeout: 3900, stdin: <<-'EOSH')
    set -x
    curl --fail http://${SERVICE_APP_NAME}.herokuapp.com -v
  EOSH
end

run forever: true