#!/usr/bin/env ruby

require_relative "../../lib/ferret"

test_freq 30

run_every_time do
  bash(name: :invalid, pattern: /fingerprint/, status: nil, stdin: <<-'EOF')
    ssh git@heroku.com "git-receive-pack 'blog.git'"
  EOF
end

run forever:true